// Copyright Epic Games, Inc. All Rights Reserved.

#include "Lumin/LuminPlatformDelegates.h"

FLuminDelegates::FLuminAppStartupArgumentsDelegate FLuminDelegates::LuminAppReceivedStartupArgumentsDelegate;

FLuminDelegates::FLuminApplicationLifetimeDelegate FLuminDelegates::DeviceHasReactivatedDelegate;
FLuminDelegates::FLuminApplicationLifetimeDelegate FLuminDelegates::DeviceWillEnterRealityModeDelegate;
FLuminDelegates::FLuminApplicationLifetimeDelegate FLuminDelegates::DeviceWillGoInStandbyDelegate;
FLuminDelegates::FLuminApplicationLifetimeFocusLostDelegate FLuminDelegates::FocusLostDelegate;
FLuminDelegates::FLuminApplicationLifetimeDelegate FLuminDelegates::FocusGainedDelegate;
